### DISCUSSION TITLE
DruidContext not working

### DISCUSSION THREAD

**Discussion by okeeffdp** [allegro/turnilo#763] [Q&A]
Hi all,

I am having trouble passing parameters to druid via the `druidContext` key in the yml config. I want to do two things: first, I want to display more than five lines on a line graph; Second I want to get the exact count distinct, not the approximate number. I'm not sure what I am doing wrong. I followed the [doc here](https://allegro.github.io/turnilo/configuration-datacubes.html#advanced-data-cube-options) The I can see the parameters in the query context that is sent to Druid, but the results do not show what I expect.

Here is a sample of the config,
```yaml
dataCubes:
  - name: my_cube
    options:
      # Context to be sent to Druid with every query executed on the data cube
      # defined as yaml key / value mappings.
      # https://druid.apache.org/docs/latest/querying/query-context.html
      druidContext:
        # Whether to use an approximate cardinality algorithm for COUNT(DISTINCT foo)s
        # https://druid.apache.org/docs/latest/configuration/index.html#broker-node-configs
        useApproximateCountDistinct: false
        # The top minTopNThreshold local results from each segment are returned
        # for merging to determine the global topN.
        minTopNThreshold: 20
        threshold: 20
```

The query sent to druid which I got `verbose: true` in the yaml.
```json
{
  "queryType": "topN",
  "dataSource": "my_cube_source",
  "intervals": "2020-11-23T23:25Z/2021-05-23T23:25Z",
  "granularity": "all",
  "context": {
    "useApproximateCountDistinct": false,
    "minTopNThreshold": 20,
    "threshold": 20,
    "timeout": 40000
  },
  "filter": {
    "type": "selector",
    "dimension": "issue_type_category",
    "value": "account security"
  },
  "dimension": {
    "type": "default",
    "dimension": "issue_type",
    "outputName": "issue_type"
  },
  "aggregations": [
    {
      "name": "count",
      "type": "longSum",
      "fieldName": "count"
    }
  ],
  "metric": "count",
  "threshold": 5
}
```

Thanks
