### ISSUE TITLE
Dimensions and measures groups

### ISSUE THREAD

**Issue by mkuthan** [allegro/turnilo#18]
As a Turnilo user I want to organise related dimensions and measures together. E.g UTM related dimensions (UTM Source, UTM Campaign, UTM Term, ...) should be presented under UTM group. 

- Related fields should be presented under single tree branch with name as separate leafs. 
- Grouping should be defined explicitly in the configuration file (additional level of aggregation under dimensions and measures elements).
- Dimension or measure name must be unique in the whole dataCube definition (not unique in the group).
- When visualization is open directly using url (e.g: from mkurl) and nested dimension or measure is used the group with this dimension or measure must be expanded.

Existing configuration structure:

```
dimensions:
    - name: dim1
      title: Dim 1
      formula: ...

    - name: dim2
      title: Dim 2
      formula: ...

    - name: dim3
      title: Dim 3
      formula: ...

measures:
    - name: measure1
      title: Measure 1
      formula: ...

    - name: measure2
      title: Measure 2
      formula: ...

    - name: measure3
      title: Measure 3
      formula: ...
```

Proposed configuration structure:

```
dimensions:
    - name: dim1
      title: Dim 1
      formula: ...

    - name: dim2
      title: Dim 2
      formula: ...

   - name: groupA
      type: group
      title: Group A
      dimensions:
        - name: dimA1
           title: Dim A 1
           formula: ...
  
        - name: dimA2
           title: Dim A 2
           formula: ...

    - name: dim3
      title: Dim 3
      formula: ...

measures:
    - name: measure1
      title: Measure 1
      formula: ...

    - name: measure2
      title: Measure 2
      formula: ...

    - name: groupA
      type: group
      title: Group A
      measures:
        - name: dimA1
           title: Dim A 1
           formula: ...
  
        - name: dimA2
           title: Dim A 2
           formula: ...

    - name: measure3
      title: Measure 3
      formula: ...
```

Default type for `dimensions` elements: "field" or "dimension".
Default type for `measures` elements: "field" or "measure".
Type for group: "group".
