### ISSUE TITLE
turnilo can't update the data source automatically

### ISSUE THREAD

**Issue by likunbyl** [allegro/turnilo#388]
I have installed Turnilo 1.14.0 in a container on my K8s platform, everything is fine, but the data source can't be updated automatically.

I originally have a wikipedia datasource, it's showing in the turnilo home page, then I added another datasource,  pageviews, but it can't be seen on the  Turnilo after several minutes.

That's my command to start the turnilo:
```
turnilo --config /usr/local/etc/turnilo.conf
```
the turnilo.conf :
```
port: 9090

clusters:
- name: druid
  url: http://druid-broker:8082
  sourceListScan: auto
  sourceListRefreshOnLoad: true
  sourceListRefreshInterval: 100000
```
