### ISSUE TITLE
Time Shift Querry error

### ISSUE THREAD

**Issue by jsercao** [allegro/turnilo#505]
## Problems or bugs?

- September 26

![image](https://user-images.githubusercontent.com/26736883/68385667-42299e00-0195-11ea-9668-25b155868b8b.png)

- September 27

![image](https://user-images.githubusercontent.com/26736883/68385713-553c6e00-0195-11ea-8717-5093c8bde1a1.png)

- Time Shift between the 26th and 27th

![image](https://user-images.githubusercontent.com/26736883/68385735-61283000-0195-11ea-9bcd-f8189aa89b64.png)

- When [show rate] is removed, it can be displayed normally

![image](https://user-images.githubusercontent.com/26736883/68385761-700ee280-0195-11ea-811d-08cca7cbe813.png)

 ##  `show rate` is the calculation measure

```yaml
- name: show_rate
        title: Show Rate
        formula: $main.sum($impression) / $main.sum($fill)
        format: 0[.]00%
```

This may be a problem with formula?  Is there any examples or documents?
