### ISSUE TITLE
Generating link error

### ISSUE THREAD

**Issue by alexnu** [allegro/turnilo#516]
When trying to generate a link using the following example found in the documentation:

```
{
  "dataCubeName": "central",
  "viewDefinitionVersion": "3",
  "viewDefinition": {
    "visualization": "totals",
    "timezone": "Etc/UTC",
    "filters": [
      {
        "type": "time",
        "ref": "time",
        "timeRanges": [
          {
            "start": "2015-09-10Z",
            "end": "2015-09-20Z"
          }
        ]
      }
    ],
    "splits": [],
    "measures": {
      "isMulti": true,
      "single": "count",
      "multi": [ "count", "delta", "added", "deleted" ]
    },
    "pinnedDimensions": [ "installs" ],
    "pinnedSort": "count"
  }
}
```

I get an error 400:
```
{
    "error": "invalid viewDefinition object",
    "message": "Dimension time not found in data cube central."
}
```

I tried replacing `"ref": "time"` with `"ref": "__time"` and it works but then the splits are not recognized. Am I doing something wrong or does the documentation need an update?

Thanks

**Comment by adrianmroz** [comment]
This endpoint validates view definition with data cube, what data cube are you using? Do you have "time" or "__time" dimension there?

And what splits are not recognised? You have empty array there.

**Comment by alexnu** [comment]
Sorry, I didn't know I can define `time` as a dimension in the configuration. Posting again with the splits:

```
{
    "dataCubeName": "central",
    "viewDefinitionVersion": "3",
    "viewDefinition": {
        "visualization": "totals",
        "timezone": "Etc/UTC",
        "filters": [
            {
                "type": "time",
                "ref": "__time",
                "timeRanges": [
                    {
                        "start": "2015-09-10Z",
                        "end": "2015-09-20Z"
                    }
                ]
            }
        ],
        "splits": [
            {
                "type": "string",
                "dimension": "campaign_id",
                "sort": {
                    "ref": "clicks",
                    "direction": "descending"
                }
            }
        ],
        "measures": {
            "isMulti": false,
            "single": "clicks"
        }
    }
}
```

And this is my configuration file:
```
dataCubes:
  - name: central
    title: Central
    ...
    dimensions:
      - name: campaign_id
        title: Campaign Id
        formula: $campaign_id
...
    measures:
      - name: clicks
        title: Clicks
        format: '0,0'
        formula: $main.sum($clicks)
...
```
