### ISSUE TITLE
Error: Custom transform can't yet be expressed as JS

### ISSUE THREAD

**Issue by realkimmy** [allegro/turnilo#693]
```yaml
dataCubes:
  - name: timezonetest
    title: timezonetest001
    clusterName: druid_cluster
    source: timezonetest111
    # The refresh rule describes how often the data cube looks for new data. Default: 'query'/PT1M (every minute)
    refreshRule:
      rule: query

    # The default timezone, expressed as an
    #       <a href="https://en.wikipedia.org/wiki/Tz_database" target="_blank">
    #       Olsen Timezone</a>, that will be selected when the user first opens this
    #       cube. Default: <code>Etc/UTC</code>.
    #defaultTimezone: Etc/UTC # <- default

    # The time period, expressed as an
    #       <a href="https://en.wikipedia.org/wiki/ISO_8601#Durations" target="_blank">
    #       ISO 8601 Duration</a>, that will be shown when the user first opens this
    #       cube. Default: <code>P1D</code>.
    #defaultDuration: P1D # <- default

    # The name of the measure that will be used for default sorting.
    #       It is commonly set to the measure that represents the count of events.
    #       Default: the first measure.
    defaultSortMeasure: count

    # The names of measures that are selected by default
    #defaultSelectedMeasures: []

    # The names of dimensions that are pinned by default (in order that they will appear in the pin bar)

    #defaultPinnedDimensions: []

    # How the dataset should be introspected
    # possible options are:
    # * none - Do not do any introspection, take what is written in the config as the rule of law.
    # * no-autofill - Introspect the datasource but do not automatically generate dimensions or measures
    # * autofill-dimensions-only - Introspect the datasource, automatically generate dimensions only
    # * autofill-measures-only - Introspect the datasource, automatically generate measures only
    # * autofill-all - (default) Introspect the datasource, automatically generate dimensions and measures
    introspection: no-autofill

    # The list of attribute overrides in case introspection get something wrong
    attributeOverrides:
    # A general attribute override looks like so:
    #
    # name: user_unique
    # ^ the name of the attribute (the column in the database)
    #
    # type: STRING
    # ^ (optional) plywood type of the attribute
    #
    # special: unique
    # ^ (optional) any kind of special significance associated with this attribute


    # The list of dimensions defined in the UI. The order here will be reflected in the UI
    dimensions:
      # A general dimension looks like so:
      #
      # name: channel
      # ^ the name of the dimension as used in the URL (you should try not to change these)
      #
      # title: The Channel
      # ^ (optional) the human readable title. If not set a title is generated from the 'name'
      #
      # kind: string
      # ^ (optional) the kind of the dimension. Can be 'string', 'time', 'number', or 'boolean'. Defaults to 'string'
      #
      # formula: $channel
      # ^ (optional) the Plywood bucketing expression for this dimension. Defaults to '$name'
      #   if, say, channel was called 'cnl' in the data you would put '$cnl' here
      #   See also the expressions API reference: https://plywood.imply.io/expressions
      #
      # url: string
      # ^ (optional) a url (including protocol) associated with the dimension, with optional token '%s'
      #   that is replaced by the dimension value to generate links specific to each value.

      - name: __time
        title: Time
        kind: time
        formula: $__time

      - name: timestamp
        title: timestamp
        kind: time
#        formula: $timestamp.cast('TIME')
        formula: $timestamp.customTransform('stringFun').cast('TIME')

      - name: PSTtime
        title: PSTtime
        formula: $PSTtime

      - name: Standardtime
        title: Standardtime
        formula: $Standardtime

      # This is the place where you might want to add derived dimensions.
      #
      # Here are some examples of possible derived dimensions:
      #
      # - name: is_usa
      #   title: Is USA?
      #   formula: $country == 'United States'
      #
      # - name: file_version
      #   formula: $filename.extract('(\d+\.\d+\.\d+)')


    # The list of measures defined in the UI. The order here will be reflected in the UI
    measures:
      # A general measure looks like so:
      #
      # name: avg_revenue
      # ^ the name of the dimension as used in the URL (you should try not to change these)
      #
      # title: Average Revenue
      # ^ (optional) the human readable title. If not set a title is generated from the 'name'
      #
      # formula: $main.sum($revenue) / $main.sum($volume) * 10
      # ^ (optional) the Plywood bucketing expression for this dimension.
      #   Usually defaults to '$main.sum($name)' but if the name contains 'min' or 'max' will use that as the aggregate instead of sum.
      #   this is the place to define your fancy formulas

      - name: count
        title: Count
        formula: $main.sum($count)

      # This is the place where you might want to add derived measures (a.k.a Post Aggregators).
      #
      # Here are some examples of possible derived measures:
      #
      # - name: ecpm
      #   title: eCPM
      #   formula: $main.sum($revenue) / $main.sum($impressions) * 1000
      #
      # - name: usa_revenue
      #   title: USA Revenue
      #   formula: $main.filter($country == 'United States').sum($revenue)

    options:
      customTransforms:
        stringFun:
          extractionFn:
            type: javascript
            function: 'function(x) { return x; }'
```
