### ISSUE TITLE
Histograms in `defaultSelectedMeasures`

### ISSUE THREAD

**Issue by jln-pl** [allegro/turnilo#725]
I have a measure defined like this:
```yml
  - name: foo_histogram
    title: Foo
    description: |
      Some desc 
    formula: $main.quantile($foo_histogram,0.90,'k=128')
    lowerIsBetter: true
```
If I add `foo_histogram` to `defaultSelectedMeasures` array and check Turnilo, I would expect `Foo p90` to be displayed in `Measures`. Unfortunately, I have `Foo p95` instead.

<img width="288" alt="turnilo" src="https://user-images.githubusercontent.com/13023902/113008913-c4927380-9177-11eb-9ef2-e318908d81eb.png">
