### ISSUE TITLE
TSV/CSV native files won't recognize data because it's all loaded in as strings

### ISSUE THREAD

**Issue by geohci** [allegro/turnilo#738]
When using a TSV or CSV file as the backend, the data that is loaded can't be displayed because the values seem to be rendered as strings. I can't figure out any config parameter that would fix this. I verified that it was rendering the data as strings by checking how d3 loads TSV/CSV files and replicating the behavior by simply putting quotes around numeric measures in a JSON.

Basic JSON config that works:
```
dataCubes:
  - name: json_example
    title: JSON Example
    clusterName: native
    source: data_sample.json
    timeAttribute: time

    refreshRule:
      rule: fixed
      time: 2021-03-01T00:00:00.000Z

    defaultSelectedMeasures: [ "mea_one" ]
    defaultPinnedDimensions: [ "dim_one" ]

    dimensions:
      - name: time
        title: Time
        formula: $time
        kind: time
        granularities: [ 'P1D', 'P1W', 'P1M', 'P3M', 'P1Y' ]

      - name: dim_one
        title: Dimension One
        formula: $dim_one

    measures:
      - name: mea_one
        title: Measure One
        formula: $main.sum($mea_one)
```
data_sample.json:
```
{"dim_one":"d1","mea_one":1,"time":"2021-03-01"}
{"dim_one":"d2","mea_one":2,"time":"2021-03-01"}
```

Basic CSV config that does not work:
```
dataCubes:
  - name: broken_csv
    title: Broken CSV
    clusterName: native
    source: data_sample.csv
    timeAttribute: time

    refreshRule:
      rule: fixed
      time: 2021-03-01T00:00:00.000Z

    defaultSelectedMeasures: [ "mea_one" ]
    defaultPinnedDimensions: [ "dim_one" ]

    dimensions:
      - name: time
        title: Time
        formula: $time
        kind: time
        granularities: [ 'P1D', 'P1W', 'P1M', 'P3M', 'P1Y' ]

      - name: dim_one
        title: Dimension One
        formula: $dim_one

    measures:
      - name: mea_one
        title: Measure One
        formula: $main.sum($mea_one)
```
data_sample.csv:
```
dim_one,mea_one,time
d1,1,2021-03-01
d2,2,2021-03-01
```

I'm not sure the right fix. It seems that D3 has an autotype that can detect numeric types (https://github.com/d3/d3-dsv) but perhaps there is an easier fix.
